BROADCAST_IP = "255.255.255.255"

OPMODE_NOT_CONFIGURED = 0
OPMODE_CONFIGURING = 1
OPMODE_CONFIGURED = 2

DEBUG = False

HW_CONF_FILENAME = "hw.json"

DEFAULT_HOSTNAME = "mywol"
DEFAULT_ESSID="ESP_WOL"
DEFAULT_PASSWORD="espwol123"

RESET_TIMER = -1
DISPLAY_TIMER = 1
BUZZER_TIMER = 2